// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Dal.Context;

namespace Server.Dal.Migrations
{
    [DbContext(typeof(ServerContext))]
    [Migration("20220507084330_FixStatistics")]
    partial class FixStatistics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Server.Dal.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Server.Dal.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Move")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RoundId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Server.Dal.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreationTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFull")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Server.Dal.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoserId");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.HasIndex("WinnerId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Server.Dal.Entities.Statistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedPaper")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedRock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsedScissors")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WinLossRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Server.Dal.Entities.Player", b =>
                {
                    b.HasOne("Server.Dal.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Dal.Entities.Round", null)
                        .WithMany("Players")
                        .HasForeignKey("RoundId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Server.Dal.Entities.Room", b =>
                {
                    b.HasOne("Server.Dal.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Server.Dal.Entities.Round", b =>
                {
                    b.HasOne("Server.Dal.Entities.Account", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId");

                    b.HasOne("Server.Dal.Entities.Room", "Room")
                        .WithOne("Round")
                        .HasForeignKey("Server.Dal.Entities.Round", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Dal.Entities.Account", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");

                    b.Navigation("Loser");

                    b.Navigation("Room");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Server.Dal.Entities.Statistics", b =>
                {
                    b.HasOne("Server.Dal.Entities.Account", "Account")
                        .WithOne("Statistics")
                        .HasForeignKey("Server.Dal.Entities.Statistics", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Server.Dal.Entities.Account", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Server.Dal.Entities.Room", b =>
                {
                    b.Navigation("Round");
                });

            modelBuilder.Entity("Server.Dal.Entities.Round", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
